[package]
name = "requires-future-cargo-web-through-dep-dep"
version = "0.1.0"
authors = ["Jan Bujak <j@exia.io>"]

[dependencies]
requires-future-cargo-web-through-dep = { path = "../requires-future-cargo-web-through-dep" }
