language: rust

dist: trusty
sudo: false

rust:
  - nightly
  - stable
  - beta

matrix:
  allow_failures:
    - rust: nightly

env:
  - TARGET=none
  - TARGET=wasm32-unknown-unknown
  - TARGET=asmjs-unknown-emscripten
  - TARGET=wasm32-unknown-emscripten

script:
  - nvm install 9
  - ./ci.sh
