[package]
name = "req-future-cargo-web-target-dep"
version = "0.1.0"
authors = ["Jan Bujak <j@exia.io>"]

[target.wasm32-unknown-emscripten.dependencies]
requires-future-cargo-web = { path = "../requires-future-cargo-web" }
