[package]
name = "req-future-cargo-web-cfg-not-dep"
version = "0.1.0"
authors = ["Jan Bujak <j@exia.io>"]

[target.'cfg(not(target_os = "emscripten"))'.dependencies]
requires-future-cargo-web = { path = "../requires-future-cargo-web" }
