[package]
name = "requires-future-cargo-web-through-dep-dev-dep"
version = "0.1.0"
authors = ["Jan Bujak <j@exia.io>"]

[dependencies]
requires-future-cargo-web-through-dev-dep = { path = "../requires-future-cargo-web-through-dev-dep" }
